name: birdhouse-docs
channels:
- defaults
- conda-forge
dependencies:
- pip
- sphinx
- nbsphinx
- nb_conda_kernels
<<<<<<< HEAD
=======
- pywps
- jupyter-client 
>>>>>>> tutorials
- pip:
  - sphinxcontrib-bibtex
