default_language_version.python = "3"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files"},
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-vcs-permalinks" },
  { id = "check-yaml"},
  { id = "mixed-line-ending"},
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.1"
hooks =[
  { id = "codespell", args = ["--config=.codespellrc"]}
]
